/**
 * 'value' : innerSelectValue
 * 'category' : категория логотипа
 * 'text' : select текст
 */

var logoList = [
    { 'value' : 'Audi', 'category' : '1', 'text' : 'Audi' },
    { 'value' : 'AudiAUDI', 'category' : '1', 'text' : 'Audi AUDI' },
    { 'value' : 'Buick', 'category' : '1', 'text' : 'Buick' },
    { 'value' : 'Isuzu', 'category' : '1', 'text' : 'Isuzu' },
    { 'value' : 'KIA2', 'category' : '1', 'text' : 'KIA 2' },
    { 'value' : 'KIA3', 'category' : '1', 'text' : 'KIA 3' },
    { 'value' : 'Chrysler', 'category' : '1', 'text' : 'Chrysler Pacifica' },
    { 'value' : 'Lincoln', 'category' : '1', 'text' : 'Lincoln' },
    { 'value' : 'Mazda', 'category' : '1', 'text' : 'Mazda' },
    { 'value' : 'MAN', 'category' : '1', 'text' : 'MAN' },
    { 'value' : 'Mercedes', 'category' : '1', 'text' : 'Mercedes' },
    { 'value' : 'Opel', 'category' : '1', 'text' : 'Opel' },
    { 'value' : 'Pontiac', 'category' : '1', 'text' : 'Pontiac' },
    { 'value' : 'Citroen2', 'category' : '1', 'text' : 'Citroen 2' },
    { 'value' : 'Toyota', 'category' : '1', 'text' : 'Toyota' },
    { 'value' : 'UAZ', 'category' : '1', 'text' : 'UAZ' },
    { 'value' : 'Haima', 'category' : '1', 'text' : 'Haima' },
    { 'value' : 'Chery', 'category' : '1', 'text' : 'Chery' },
    { 'value' : 'CheryCHERY', 'category' : '1', 'text' : 'Chery CHERY' },
    { 'value' : 'Jaguar', 'category' : '1', 'text' : 'Jaguar' },
    { 'value' : 'Bogdan', 'category' : '2', 'text' : 'Bogdan' },
    { 'value' : 'Hover', 'category' : '2', 'text' : 'Hover' },
    { 'value' : 'Jeep', 'category' : '2', 'text' : 'Jeep' },
    { 'value' : 'Daewoo', 'category' : '2', 'text' : 'Daewoo' },
    { 'value' : 'Infiniti', 'category' : '2', 'text' : 'Infiniti' },
    { 'value' : 'KamazKAMAZ', 'category' : '2', 'text' : 'Kamaz KAMAZ' },
    { 'value' : 'LADA', 'category' : '2', 'text' : 'LADA' },
    { 'value' : 'Lexus', 'category' : '2', 'text' : 'Lexus' },
    { 'value' : 'LexusLEXUS', 'category' : '2', 'text' : 'Lexus LEXUS' },
    { 'value' : 'Lifan', 'category' : '2', 'text' : 'Lifan' },
    { 'value' : 'Mini', 'category' : '2', 'text' : 'Mini' },
    { 'value' : 'Mitsubishi', 'category' : '2', 'text' : 'Mitsubishi' },
    { 'value' : 'Mitsubishi2', 'category' : '2', 'text' : 'Mitsubishi 2' },
    { 'value' : 'Renault', 'category' : '2', 'text' : 'Renault' },
    { 'value' : 'SsangYong', 'category' : '2', 'text' : 'SsangYong' },
    { 'value' : 'Suzuki', 'category' : '2', 'text' : 'Suzuki' },
    { 'value' : 'Fiat', 'category' : '2', 'text' : 'Fiat' },
    { 'value' : 'Freightliner', 'category' : '2', 'text' : 'Freightliner' },
    { 'value' : 'Volkswagen', 'category' : '2', 'text' : 'Volkswagen' },
    { 'value' : 'Ford', 'category' : '2', 'text' : 'Ford' },
    { 'value' : 'Hyundai', 'category' : '2', 'text' : 'Hyundai' },
    { 'value' : 'Chery2', 'category' : '2', 'text' : 'Chery2' },
    { 'value' : 'Chevrolet', 'category' : '2', 'text' : 'Chevrolet' },
    { 'value' : 'ChevroletCHEVROLET', 'category' : '2', 'text' : 'Chevrolet CHEVROLET' },
    { 'value' : 'BMW', 'category' : '3', 'text' : 'BMW' },
    { 'value' : 'Volvo', 'category' : '3', 'text' : 'Volvo' },
    { 'value' : 'GAZ', 'category' : '3', 'text' : 'GAZ' },
    { 'value' : 'Geely', 'category' : '3', 'text' : 'Geely' },
    { 'value' : 'Geely2', 'category' : '3', 'text' : 'Geely 2' },
    { 'value' : 'Dodge', 'category' : '3', 'text' : 'Dodge' },
    { 'value' : 'CadillacCADILLAC', 'category' : '3', 'text' : 'Cadillac CADILLAC' },
    { 'value' : 'Daewoo2', 'category' : '3', 'text' : 'Daewoo 2' },
    { 'value' : 'KIA1', 'category' : '3', 'text' : 'KIA 1' },
    { 'value' : 'LandRover', 'category' : '3', 'text' : 'Land Rover' },
    { 'value' : 'Nissan', 'category' : '3', 'text' : 'Peugeot' },
    { 'value' : 'Rolls-Royce', 'category' : '3', 'text' : 'Rolls-Royce' },
    { 'value' : 'Seat', 'category' : '3', 'text' : 'Seat' },
    { 'value' : 'CitroenCITROEN', 'category' : '3', 'text' : 'Citroen CITROEN' },
    { 'value' : 'FordMustang', 'category' : '3', 'text' : 'Ford Mustang' },
    { 'value' : 'HummerH2', 'category' : '3', 'text' : 'Hummer H2' },
    { 'value' : 'HummerH3', 'category' : '3', 'text' : 'Hummer H3' },
    { 'value' : 'Skoda', 'category' : '3', 'text' : 'Skoda' },
    { 'value' : 'Skoda2', 'category' : '3', 'text' : 'Skoda 2' },
    { 'value' : 'AlfaRomeo', 'category' : '4', 'text' : 'Alfa Romeo' },
    { 'value' : 'AlfaRomeoALFAROMEO', 'category' : '4', 'text' : 'Alfa Romeo ALFA ROMEO' },
    { 'value' : 'Bugatti', 'category' : '4', 'text' : 'Bugatti' },
    { 'value' : 'Porsche', 'category' : '4', 'text' : 'Porsche' },
    { 'value' : 'Seat2', 'category' : '4', 'text' : 'Seat 2' },
    { 'value' : 'Faw', 'category' : '4', 'text' : 'Faw' },
    { 'value' : 'Ferrari', 'category' : '4', 'text' : 'Ferrari' },
    { 'value' : 'Honda2', 'category' : '4', 'text' : 'Honda 2' },
];


module.exports = logoList;
